---
- hosts: ubuntu
  tasks:
    - name: Ansible Loop
      debug: 
        msg: "{{ item }}"
      with_items: 
        - "Hello1"
        - "Hello2"
        - "Hello3"
      when: ansible_os_family == "Debian" and ansible_distribution_major_version == "18"
