---
- hosts: webserver_linux
  tasks:
    - name: Print Ansible Facts
      debug:
        msg: > 
                The Default address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }} 