---
- hosts: webserver_linux
  tasks:
    - name: Install latest package of firewalld
      yum: firewalld
      state: latest
    - name: Start and Enable firewalld service
      service:
        name: firewalld
        enabled: True
        state: started
    - name: Permit http service
      firewalld:
        service: httpd
        permanent: True
        state: enabled
        immidiate: yes
    - name: Create simple HTML web page
      copy:
        content: "Welcome to Ansible Learning Course\n"
        dest: /var/www/html/index.html
    - name: Defining Web Server Name
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerName ec2-18-234-226-216.compute-1.amazonaws.com:80
        insertafter: "#ServerName"
    - name: Update entry in /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: 18.234.226.216  ec2-18-234-226-216.compute-1.amazonaws.com:80
