---
- hosts: webserver_linux
  vars:
    remote_dir: /etc/ansible/facts.d
    fact_file: custom.fact
  tasks:
    - name: Create a remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Copy a file
      copy:
        src: "{{ fact_file }}"
        dest: "{{ remote_dir }}"
