#!/bin/bash

while true
do
  echo -e "Please Select your choice from below menu\n"
  echo -e " 1. Pre-Validation \n"
  echo -e " 2. User Administration \n"
  echo -e " 3. Run Ad Hoc Commands \n"
  echo -e " 0. Exit \n"
  read choice
  case $choice in

  0)
  break
  ;;
  1)
  echo " Welcome to Pre-Validation"
  sleep 4
  ;;
  2)
  while true
  do
    echo -e " 1. User Creation \n"
    echo -e " 2. User Removal \n"
    echo -e " 3. Group Add \n"
    echo -e " 0. Exit \n"
    read choice
    case $choice in

    0)
    break
    ;;
    1)
    echo -e "Welcome to User Creation \n"
    ;;
    2)
    echo -e "Welcome to User Removal \n"
    ;;
    3)
    echo -e "Welcome to Group Add \n"
    ;;
    *)
    echo -e "Wrong Choice! \n"
    read dummy
    continue
    ;;
    esac
    done

  ;;
  3)
  echo " Welcome to Ad Hoc Commands"
  ;;
  *)
  echo -e "Wrong Choice! \n"
  read dummy
  continue
  ;;
  esac
done  
