#!/bin/bash

while true
do

  echo "Please Select your choice from below menu"
  echo " 1. Pre-Validation"
  echo " 2. User Administration"
  echo " 3. Run Ad Hoc Commands"
  echo " 0. Exit"
  read choice
  case $choice in


  0)
  break
  ;;
  1)
  echo "Welcome to Pre-Validation"
  ;;
  2)
  echo "Welcome to User Administartion"
  ;;
  3)
  echo "Welcome to Ad Hoc Commands"
  ;;
  esac
done  


