#!/bin/bash

while true
do

  echo -e "Please Select your choice from below menu\n"
  echo -e " 1. Pre-Validation\n"
  echo -e " 2. User Administration\n"
  echo -e " 3. Run Ad Hoc Commands\n"
  echo -e " 0. Exit\n"
  read choice
  case $choice in

  0)
  break
  ;;
  1)
  echo " Welcome to Pre-Validation"
  sleep 4
  ;;
  2)
  echo " Welcome to User Administration"
  sleep 4
  ;;
  3)
  echo " Welcome to Ad Hoc Commands"
  ;;
  *)
  echo -e "Wrong Choice!\n"
  read dummy
  continue
  ;;
  esac
done  
