#!/bin/bash
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
NORMAL="\033[0;39m"
clear
try="Yes"
target="None"
my_head()
{

echo -e $BIYellow"-------------------------------------------------------------------------------------------------------------------------------------------"
        echo -e " Automation Tool to automate day to day Unix Tasks!!\c"
        echo -e "\tTrial=$try \c"
        echo -e "\tTarget Servers : $target"
        echo -e "-------------------------------------------------------------------------------------------------------------------------------------------"$NORMAL
}

while true
do
my_head
  echo -e $BICyan"Please Select your choice from below menu\n"
  echo -e " 1. Pre-Validation \n"
  echo -e " 2. User Administration \n"
  echo -e " 3. Run Ad Hoc Commands \n"
  echo -e " 0. Exit \n"$NORMAL
  read choice
  case $choice in

  0)
  break
  ;;
  1)
  echo " Welcome to Pre-Validation"
  sleep 4
  ;;
  2)
  while true
  do
    echo -e $BIPurple" 1. User Creation \n"
    echo -e " 2. User Removal \n"
    echo -e " 3. Group Add \n"
    echo -e " 0. Exit \n"$NORMAL
    read choice
    case $choice in

    0)
    break
    ;;
    1)
    echo -e "Welcome to User Creation \n"
    ;;
    2)
    echo -e "Welcome to User Removal \n"
    ;;
    3)
    echo -e "Welcome to Group Add \n"
    ;;
    *)
    echo -e "Wrong Choice! \n"
    read dummy
    continue
    ;;
    esac
    done

  ;;
  3)
  echo " Welcome to Ad Hoc Commands"
  ;;
  *)
  echo -e "Wrong Choice! \n"
  read dummy
  continue
  ;;
  esac
done  
