---
- hosts: all
  become: true
  become_user: root
  vars:
    password: $6$QC/aG8bv5Q$D6h9ouB1YYPTeI1SFRRGMh6W3sDtbZ/ICsRTpdgRTXapIs54vqCuEjQqbrSDdKmpnsT6F5ulIMnxfIgfRAUVt1
    userid: usrid
    sgrp: sgrnms
    comments: cmmts
    username: usernme
    pgrp: pgrnm
    hme: hmg
  tasks:
  - name: User Exist
    shell: id {{ username }}
    register: user_exist
    ignore_errors: True
  - name: User Creation
    user: name={{ username }} uid={{ userid }} home={{ hme }} comment={{ comments }} password={{ password }} group={{pgrp}} groups={{ sgrp }} append=yes
    when: user_exist.rc != 0 and ansible_distribution == "RedHat"
    register: user_creation
  - debug: msg="User Name {{ username }} is already existing on the {{ ansible_hostname }}"
    when: user_exist.rc == 0

