---
- hosts: myenv
  become: true
  become_user: root
  tasks:
  - name: User Removal Task
    user: name=johndavid state=absent remove=yes
    register: userremoval
  - debug: msg="User johndavid has been removed from {{ ansible_hostname }}"
    when: userremoval.changed
  - debug: var=userremoval
