---
- hosts: webserver
  tasks:
    - name: Verify App/Database status
      shell: if ps -eaf| egrep 'httpd' | grep -v grep > /dev/null; then echo 'Process is running'; else echo 'Process is not running'; fi
      ignore_errors: true
      register: appr_proc_check
    - debug: msg="{{  appr_proc_check.stdout }}" 
    - name: Decision point to start patching
      fail:
             msg="{{ inventory_hostname }} having running application, please stop first and attempt patching"  
      when:  appr_proc_check.stdout == 'Process is running'    