---
- hosts: webserver
  tasks:
    - name: Verify App/Database status
      shell: if ps -eaf| egrep 'httpd' | grep -v grep > /dev/null; then echo 'Process is running'; else echo 'Process is not running'; fi
      ignore_errors: true
      register: appr_proc_check
    - debug: msg="{{  appr_proc_check.stdout }}" 
    - name: Decision point to start patching
      fail:
             msg="{{ inventory_hostname }} having running application, please stop first and attempt patching"  
      when:  appr_proc_check.stdout == 'Process is running'  
    - name: Copy Kernel Repo file 
      copy:
        src: /ansible_study/Introduction/playbooks/patching/kernel.repo
        dest: /etc/yum.repos.d
    - name: Current Kernel Version
      shell: uname -r
      register: curr_ker
    - name: Initiating Patching
      yum: 
        name=kernel 
        state=latest
      register: yum_update
    - debug: msg="kernel has been updated"
      when: yum_update.rc == 0 
    - name: Check if reboot is required
      shell: kernel_new=$(rpm -qa --last kernel | head -1| awk '{print $1}' | sed 's/kernel-//g'); kernel_now=$(uname -r);  if [[ $kernel_new != $kernel_now]]; then echo "Reboot is required"; else echo "Reboot is not required"; fi
      ignore_errors: True
      register: reboot_check
    - debug: msg="{{ reboot_check.stdout  }}" 
    - name: Reboot after patching
      command: reboot
      when:  reboot_check.stdout == 'Reboot is required'  


